(defun bubble-sort (x)
  (let ((l (length x)))
    (dotimes (n l)
      (let ((swapped nil))
       (dotimes (m (- l 1))
         (let ((num1 (nth m x))
               (num2 (nth (+ m 1) x)))
                          (if (> num1 num2)
               (let ((temp num1))
                 (setf (nth m x) num2)
                 (setf (nth (+ m 1) x) temp)
                 (setf swapped T)))
           ))
       (when (not swapped)
         (return x))))))