(defun Main()
(terpri)
(setq Result 0)
(princ "Enter The First Number: ")
(setq n (read))
(princ "Enter The Second Number: ")
(setq m (read))
(loop while (> n 0)
do(
progn(setq d1 (mod n 10))
(setq tt (+ m 0))
(loop while (> tt 0)
do(
progn(setq d2 (mod tt 10))
(setq d (* d1 d2))
(setq Result (+ Result d))
(setq tt (floor tt 10))
)
)
(setq n (floor n 10))
)
)
(princ "Result: ")
(write Result))
(Main)
